ForekRequisition/ForekRequisition/Models/ApprenticeResults.cs
using ApprenticeApplications.Models;
using ApprenticeApplications.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace ForekRequisition.Models
{
    public class ApprenticeResult : Base
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        [MaxLength(20)]
        [MinLength(3)]
        public string LastName { get; set; }

        [Display(Name = "RSA ID Number")]

        [MaxLength(13)]
        public string IdNumber { get; set; }

        [MaxLength(10)]
        public string? Cellphone { get; set; }

        [Display(Name = "Does Applicant Qualify")]
        public eDecision DoesApplicantQualify { get; set; }
        public eProgramme Programme { get; set; }

        [Display(Name = "Programme Type")]
        public eProgrammeType ProgrammeType { get; set; }

        [DataType(DataType.MultilineText)]
        public string? Recommendation { get; set; }

        [Display(Name = "Percentage(%) Obtained")]
        public double PercentageObtained { get; set; } = 0;

        [Display(Name = "Add More")]
        public bool AddMore { get; set; } = false;

        [Display(Name = "Municipality")]
        public eMunicipality District { get; set; }

        [Display(Name = "District")]
        public eDistrict? MunicipalDistrict { get; set; }
        public eGender Gender { get; set; }

        [Display(Name = "Approval Status")]
        public eApproval IsApproved { get; set; } = eApproval.NotApproved;


    }
}

ForekRequisition/ForekRequisition/Controllers/API/ApprenticeResultsAPI/ApprenticeResultsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ForekRequisition.Data;
using ForekRequisition.Models;

namespace ForekRequisition.Controllers.API.ApprenticeResultsAPI
{
    [Route("api/[controller]")]
    [ApiController]
    public class ApprenticeResultsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public ApprenticeResultsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/ApprenticeResults
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ApprenticeResult>>> GetApprenticeResult()
        {
            return await _context.AppResults.ToListAsync();
        }

        // GET: api/ApprenticeResults/5
        [HttpGet("{id}")]
        public async Task<ActionResult<ApprenticeResult>> GetApprenticeResult(Guid id)
        {
            var apprenticeResult = await _context.AppResults.FindAsync(id);

            if (apprenticeResult == null)
            {
                return NotFound();
            }

            return apprenticeResult;
        }

        // PUT: api/ApprenticeResults/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutApprenticeResult(Guid id, ApprenticeResult apprenticeResult)
        {
            if (id != apprenticeResult.Id)
            {
                return BadRequest();
            }

            _context.Entry(apprenticeResult).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ApprenticeResultExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/ApprenticeResults
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<ApprenticeResult>> PostApprenticeResult(ApprenticeResult apprenticeResult)
        {
            _context.AppResults.Add(apprenticeResult);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetApprenticeResult", new { id = apprenticeResult.Id }, apprenticeResult);
        }

        // DELETE: api/ApprenticeResults/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteApprenticeResult(Guid id)
        {
            var apprenticeResult = await _context.AppResults.FindAsync(id);

            if (apprenticeResult == null)
            {
                return NotFound();
            }

            _context.AppResults.Remove(apprenticeResult);

            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool ApprenticeResultExists(Guid id)
        {
            return _context.AppResults.Any(e => e.Id == id);
        }
    }
}

ForekRequisition/ForekRequisition/Controllers/AuthController.cs
using ApprenticeApplications.Models.Enums;
using AspNetCoreHero.ToastNotification.Abstractions;
using CMS.Models.ViewModels;
using ForekRequisition.Data;
using ForekRequisition.Models;
using ForekRequisition.Models.Helpers;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace ForekRequisition.Controllers
{
    public class AuthController : Controller
    {
        private readonly ApplicationDbContext _context;
        public INotyfService _notfy { get; }
        public AuthController(ApplicationDbContext context, INotyfService notfy)
        {
            _context = context;

            _notfy = notfy;
        }


        [HttpGet]
        public IActionResult OnSignIn()
        {
            //UserLogin login = new UserLogin();

            //login.ReturnUrl = ReturnUrl;

            // return View(login);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnSignIn(UserLogin user, string? ReturnUrl = "")
        {
            string message = "";

            if (!String.IsNullOrEmpty(user.EmailID))
            {
                if (!String.IsNullOrEmpty(user.Password))
                {
                    if (ModelState.IsValid)
                    { 

                        var userInfo = await _context.Users.Where(m => m.Email == user.EmailID 

                        && m.Password == Helper.EncryptInput(user.Password)).

                        FirstOrDefaultAsync();

                        if (userInfo != null)
                        {
                            var claims = new List<Claim>()
                            {
                               new Claim(ClaimTypes.NameIdentifier,userInfo.Id.ToString()),
                               new Claim(ClaimTypes.Name, userInfo.Name),
                               new Claim(ClaimTypes.Surname, userInfo.LastName),
                               new Claim(ClaimTypes.NameIdentifier, userInfo.Id.ToString()),
                               new Claim(ClaimTypes.Role, userInfo.Role.ToString()),
                               new Claim("ApprenticeProjCookie","Code")
                            };

                            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                            var principal = new ClaimsPrincipal(identity);
                            

                           var currentUserName = identity.FindFirst(ClaimTypes.Name);

                           var currentUserSurname = identity.FindFirst(ClaimTypes.Surname);

                           var currentUserId = identity.FindFirst(ClaimTypes.NameIdentifier);

                            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties()
                            {
                                IsPersistent = user.RememberMe

                            });

                            if (!userInfo.IsEmailVerified)
                            {
                                ViewBag.Message = "Please verify your email first";

                                _notfy.Error("email not verified");

                                return View();

                            }


                            if (string.Compare(Helper.EncryptInput(user.Password), userInfo.Password) == 0)
                            {
                                int timeout = user.RememberMe ? 525600 : 20;

                                if (Url.IsLocalUrl(ReturnUrl))
                                {
                                    return Redirect(ReturnUrl);
                                }
                                else
                                {

                                    Helper.loggedInUser = $"{userInfo.Name} {userInfo.LastName}";

                                    userInfo.LastLoginDate = DateTime.Now.ToString();

                                    if(userInfo.Role == eRole.SystemAdministrator)
                                    {
                                        return RedirectToAction("Index", "Home");

                                    }
                                    else
                                    {
                                        return RedirectToAction("ApplicantRegister", "Applicant");

                                    }

                                }

                            }
                            else
                            {
                                message = "Invalid credentials provided";

                                _notfy.Error("Invalid credentials provided");
                            }
                        }
                        else
                        {
                            message = "Error: An error occured!";

                            _notfy.Error("Error: An error occured!");

                        }
                    }
                }
                else
                {
                    message = "Error: Invalid or Empty Password!";

                    _notfy.Error("Error: Invalid or Empty Password!");
                }
            }
            else
            {
                message = "Error: Invalid or Empty Email Provided!";

                _notfy.Error("Error: Invalid or Empty Email Provided!");
            }

            ViewBag.Message = message;

            return View();
        }

        public IActionResult UserSignUp()
        {
            return View();
        }

        public IActionResult ModifyUserInfo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> ModifyUserInfo(User user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoesUserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction(nameof(Index));

        }



        [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> UserSignUp(User user)
            {

                bool Status = false;

                string message = "";

                #region Generate Activation Code 

                string time = DateTime.Now.ToString("hh:mm tt");

                string date = DateTime.Now.ToString("dddd, dd MMMM yyyy") + " " + time;

                user.ActivationCode = Helper.GenerateGuid();

                user.LastLoginDate = date;

                user.ResetPasswordCode = "";

                user.Id = Helper.GenerateGuid();

                #endregion

                #region  Password Hashing 
                user.Password = Helper.EncryptInput(user.Password);
                user.ConfirmPassword = Helper.EncryptInput(user.ConfirmPassword);
                #endregion

                //Set to false before production
                user.IsEmailVerified = true;

                user.IsActive = true;
                user.CreatedOn = DateTime.Now;
                user.ResetPasswordCode = "";
                user.Role = eRole.Applicant;

                if (ModelState.IsValid)
                {


                    #region Save to Database

                    try
                    {

                        await _context.Users.AddAsync(user);

                        await _context.SaveChangesAsync();

                        ViewData["successMessage"] = $"User Successfully Registered";

                        //SendVerificationLinkEmail(user.Email, user.ActivationCode.ToString());
                        //message = " Registration successfully done. Account activation link " +
                        //    " has been sent to your email: " + user.Email + "\nKindly click on the link to activate your account.\n" +
                        //    " Yours In-Community";
                        Status = true;

                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                    #endregion
                }
                else
                {
                    message = "Registration Successful";
                }

                ViewBag.Message = message;
                ViewBag.Status = Status;

                return View(user);
            }
        


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            Helper.loggedInUser = String.Empty;

            return RedirectToAction("OnSignIn");
        }

        private bool DoesUserExists(Guid id)
        {
            return _context.Users.Any(e => e.Id == id);
        }


    }
}

ForekRequisition/ForekRequisition/Views/ApprenticeResults/Delete.cshtml
@model ForekRequisition.Models.ApprenticeResult

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApprenticeResult</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cellphone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cellphone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoesApplicantQualify)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoesApplicantQualify)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProgrammeType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProgrammeType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recommendation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recommendation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PercentageObtained)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PercentageObtained)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ForekRequisition/ForekRequisition/Views/ApprenticeResults/Details.cshtml
@model ForekRequisition.Models.ApprenticeResult

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ApprenticeResult</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cellphone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cellphone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoesApplicantQualify)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoesApplicantQualify)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProgrammeType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProgrammeType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recommendation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recommendation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PercentageObtained)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PercentageObtained)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ForekRequisition/ForekRequisition/Views/ApprenticeResults/Index.cshtml
@model IEnumerable<ForekRequisition.Models.ApprenticeResult>


@{
    Layout = null;

    ViewData["Title"] = "Results";

    
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css" />
<script src="https://use.fontawesome.com/65d1ed3b51.js"></script>

<br />

<div class="alert alert-dark mr-5 ml-5" role="alert">
    <div class="btn-group">
          <a asp-action="SetApprenticeResults" asp-controller="ApprenticeResults" class="btn btn-outline-danger"><i class="fa fa-plus"> Add New</i></a>
           <a asp-action="Logout" asp-controller="Auth" class="btn btn-dark"><i class="fa fa-sign-out"> Logout</i></a>
    </div>
</div>
<div class="card shadow mb-4">
   <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
           Candidates who wrote the selection test
        </h6>
  </div>

  <div class="card-body">

      <div class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
          <table class="table thead-dark table-sm apprentices">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
               Surname
            </th>
            <th>
                ID
            </th>

             <th>
               @Html.DisplayNameFor(model => model.Programme)

                </th>

             <th>
              District
             </th>

             <th>
                 Mark
             </th>
              <th>
                Gender
             </th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNumber)
            </td>
              <td>
                @Html.DisplayFor(modelItem => item.Programme)
            </td>

             <td>
                @Html.DisplayFor(modelItem => item.MunicipalDistrict)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PercentageObtained)%
            </td>

             <td>
                @Html.DisplayFor(modelItem => item.Gender) 
            </td>
            
            <td>
  
                <div class="btn-group">
                <a asp-action="ApprenticeEdit" asp-route-id="@item.Id"> Open</a> 
                </div>

            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"></script>

  
      </div>

  </div>
</div>

<script>
    $(document).ready(function(){

        $('.apprentices').DataTable({

            initComplete: function(){

                this.api().columns([3,4,6]).every(function (){

                    var column = this;
                    var select = $('<select><option value=""></option></select>')
                    .appendTo($(column.header()).empty())
                    .on('change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );

                        column.search(val ? '^' + val + '$' : '', true, false)
                        .draw();
                    });

                    column.data().unique().sort().each(function (d,j){

                        select.append('<option value="'+d+'">' + d + '</option>')
                    });
                });
            }

        });

    });
</script>

ForekRequisition/ForekRequisition/Views/ApprenticeResults/OnGetApplicantResponse.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<p>hhh</p>

ForekRequisition/ForekRequisition/Views/ApprenticeResults/OnNotComplete.cshtml
<br />
<br />

<div class="alert alert-danger" role="alert">
  <strong>Script NOT marked</strong><br /><hr />
  Ooops,unfortunately your script is still not yet marked
 <br />

  However, keep checking<br /><br />
  <a class="btn btn-dark" asp-action="ApplicantRegister" asp-controller="Applicant">close</a>


</div>

ForekRequisition/ForekRequisition/Views/ApprenticeResults/ResultsSearch.cshtml
<link href="~/css/dashboard.css" rel="stylesheet" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css" />
<script src="https://use.fontawesome.com/65d1ed3b51.js"></script>

<br />
<br />

<div class="card shadow mb-4">

  <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            Apprentice Results
        </h6>
  </div>

<div class="card-body">

      <div class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
        <table class="table thead-dark table-sm">
  <thead>
    <tr>
      <th scope="col">Full Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">ID Number</th>
      <th scope="col">Programme</th>
      <th scope="col">Recommendation</th>
      <th scope="col">Percentage(%)</th>
    
      
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>@ViewData["Name"]</td>
      <td>@ViewData["LName"]</td>
      <td>@ViewData["Id"]</td>
      <td>@ViewData["Programme"]</td>
      <td>@ViewData["Reco"]</td>
      <td>@ViewData["Per"]</td>
    </tr>
  </tbody>
</table>
<br />
<div class="UserInfoDisplay">
    <div class="col-md-12">
        <div class="card border-left-dark shadow h-100 py-2">
            <div class="card-body">
                <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-danger">Urgent Notice for @ViewData["Name"] @ViewData["LName"]</h6>
                </div>
                <div class="card-body">
                    <div class="btn-group">
                   <a class="btn btn-outline-dark" asp-route-applicantId="@ViewData["UserId"]" asp-action="OnSignOffer" asp-controller="ApplicantOffer"><i class="fa fa-check"></i> Im Available</a>
                   <a class="btn btn-dark" id="btnPlumber" asp-route-applicantId="@ViewData["UserId"]" asp-action="OnSignOffer" asp-controller="ApplicantOffer"><i class="fa fa-check"></i> Im NOT Available</a>
                   <a class="btn btn-outline-dark" href="~/Auth/Logout"><i class="fa fa-close"></i> Close Page</a>
                     </div>
                </div>
                </div>
            </div>
        </div>
  </div>
</div>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</div>

</div>
</div>

<script>
    $(document).ready(function () {

        var status = '@ViewData["Reco"]';

        if(status.includes("Approved")){
              $('.UserInfoDisplay').show();
        }else{
            $('.UserInfoDisplay').hide();

        }

         $("#btnPlumber").on("click", function () {
             $('#welderPlumber').hide();
             $('#btnPlumber').hide();
          });
          
    });
</script>